modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]]
modId="tinactory"
version="${file.jarVersion}"
displayName="Tinactory"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
#logoFile="tinactory.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="Tiny"

[[dependencies.tinactory]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tinactory]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tinactory]]
modId = "tinycorelib"
mandatory = true
versionRange = "[1.18.2-0.0.1,)"
ordering = "NONE"
side = "BOTH"

